"""Typed Web UI QA primitives used by :class:`browser_use.Agent`."""

from browser_use.qa.bundle import QABundle, QABundleManifest, QABundleRevision, qa_content_hash
from browser_use.qa.chrome_recorder import (
	ChromeRecorderFlow,
	ChromeRecorderPlaybackError,
	ChromeRecorderPlaybackResult,
	ChromeRecorderPlaybackStatus,
	ChromeRecorderPlayer,
	ChromeRecorderStep,
	ChromeRecorderStepResult,
	ChromeRecorderStepStatus,
	export_agent_history_to_chrome_recorder,
	load_chrome_recorder_flow,
	write_agent_history_chrome_recorder_flow,
	write_chrome_recorder_flow,
)
from browser_use.qa.compiler import QATaskCompiler, WebUITestCaseDraft, WebUITestStepDraft, extract_task_urls
from browser_use.qa.evaluation import QAEvaluationMetrics, QAEvaluationSample, evaluate_qa_runs
from browser_use.qa.judge import judge_test_step
from browser_use.qa.llm import invoke_qa_structured
from browser_use.qa.navigation import NavigationScope
from browser_use.qa.reporting import (
	qa_html_report,
	qa_junit_xml,
	write_qa_html_report,
	write_qa_json_report,
	write_qa_junit_report,
)
from browser_use.qa.views import (
	ActionCompletionStatus,
	ActionExpectationProof,
	ActionReceipt,
	ActionTargetProof,
	BrowserEvidenceSnapshot,
	EvidenceArtifact,
	EvidenceKind,
	EvidenceQuality,
	ExpectationSource,
	ExpectationStatus,
	FailureCode,
	FailureOrigin,
	FinishTestStepAction,
	PreconditionMode,
	PreconditionStatus,
	QACleanupResult,
	QAPhaseTiming,
	QAPlanSnapshot,
	QAPlanStep,
	QAPrecondition,
	QAPreconditionResult,
	QARunResult,
	QARunStatus,
	QAStepResult,
	QAStepStatus,
	ReplayAssertion,
	ReplayAssertionKind,
	RequirementReference,
	RequirementSource,
	ReviewRecord,
	SideEffectLevel,
	StepEvidence,
	StepJudgement,
	StepOperationKind,
	WebUITestCase,
	WebUITestStep,
)

__all__ = [
	'ActionCompletionStatus',
	'ActionExpectationProof',
	'ActionReceipt',
	'ActionTargetProof',
	'BrowserEvidenceSnapshot',
	'ChromeRecorderFlow',
	'ChromeRecorderPlaybackError',
	'ChromeRecorderPlaybackResult',
	'ChromeRecorderPlaybackStatus',
	'ChromeRecorderPlayer',
	'ChromeRecorderStep',
	'ChromeRecorderStepResult',
	'ChromeRecorderStepStatus',
	'EvidenceArtifact',
	'EvidenceKind',
	'EvidenceQuality',
	'ExpectationSource',
	'ExpectationStatus',
	'FailureOrigin',
	'FailureCode',
	'FinishTestStepAction',
	'NavigationScope',
	'QAPhaseTiming',
	'QAPlanSnapshot',
	'QAPlanStep',
	'QACleanupResult',
	'QARunResult',
	'QARunStatus',
	'QAPrecondition',
	'QAPreconditionResult',
	'QAStepResult',
	'QAStepStatus',
	'PreconditionMode',
	'PreconditionStatus',
	'QABundle',
	'QABundleManifest',
	'QABundleRevision',
	'QAEvaluationMetrics',
	'QAEvaluationSample',
	'RequirementReference',
	'RequirementSource',
	'ReplayAssertion',
	'ReplayAssertionKind',
	'ReviewRecord',
	'SideEffectLevel',
	'StepOperationKind',
	'QATaskCompiler',
	'StepEvidence',
	'StepJudgement',
	'WebUITestCase',
	'WebUITestCaseDraft',
	'WebUITestStep',
	'WebUITestStepDraft',
	'extract_task_urls',
	'evaluate_qa_runs',
	'export_agent_history_to_chrome_recorder',
	'invoke_qa_structured',
	'judge_test_step',
	'load_chrome_recorder_flow',
	'qa_content_hash',
	'qa_html_report',
	'qa_junit_xml',
	'write_agent_history_chrome_recorder_flow',
	'write_chrome_recorder_flow',
	'write_qa_html_report',
	'write_qa_json_report',
	'write_qa_junit_report',
]
